url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ivan Herman" # the name of your site, e.g. ACME Corp.

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
destination: output
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules/
  - output
  - Attic
  - update
